name: CD

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-push:
    uses: coscene-io/cicd-templates/.github/workflows/image-push-go.yml@main
    with:
      project: coscout
    secrets: inherit

  upgrade-server:
    needs:
      - image-push
    uses: coscene-io/cicd-templates/.github/workflows/sub-chart-upgrade.yml@main
    with:
      deployment-name: coscene-coscout
    secrets: inherit
