name: Lint and Test

# Reference to the two tutorials below:
# https://github.com/marketplace/actions/install-poetry-action
# https://testdriven.io/tips/810f9bb5-c9df-479d-baa4-290c7e0779f1/

on:
  pull_request:
    branches:
      - master
  workflow_call:
    secrets:
      COS_API_KEY:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  lint-n-test:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Install dependencies and api key
        run: |
          pip install -e .[dev] --extra-index-url https://buf.build/gen/python
      - name: Lint with flake8
        run: flake8 cos --count --show-source --statistics
      - name: Test with pytest
        run: |
          pytest -p no:logging -p no:warnings --cov=cos --cov-report=xml
