name: Compile the offline installation package

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      cosVersion:
        description: cos version
        type: choice
        options:
          - latest
          - beta
        default: latest

jobs:
  package-zip-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Tar gz file
        run: |
          chmod +x script/package.sh
          script/package.sh --cos_version=${{ inputs.cosVersion }}

      - name: Upload Tar gz file
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.ACK_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.ACK_ACCESS_KEY_SECRET }}
          region: oss-cn-hangzhou
          bucket: coscene-download
          assets: |
            /home/runner/cos_binaries.tar.gz:/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries.tar.gz
            /home/runner/cos_binaries_arm64.tar.gz:/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries_arm64.tar.gz
            /home/runner/cos_binaries_arm.tar.gz:/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries_arm.tar.gz
            /home/runner/cos_binaries_amd64.tar.gz:/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries_amd64.tar.gz

      - name: Upload to S3
        run: |
          aws s3 cp /home/runner/cos_binaries.tar.gz s3://coscene-download/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries.tar.gz
          aws s3 cp /home/runner/cos_binaries_arm64.tar.gz s3://coscene-download/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries_arm64.tar.gz
          aws s3 cp /home/runner/cos_binaries_arm.tar.gz s3://coscene-download/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries_arm.tar.gz
          aws s3 cp /home/runner/cos_binaries_amd64.tar.gz s3://coscene-download/coscout/v2/tar/${{ inputs.cosVersion }}/cos_binaries_amd64.tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ARTIFACTS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ARTIFACTS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: 'us-east-1'
